apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
  labels:
    app: minecraft
    version: "3.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
        version: "3.0"
    spec:
      containers:
      - name: minecraft
        image: openhack/minecraft-server:2.0
        ports:
        - containerPort: 25565
          protocol: TCP
        - containerPort: 25575
          protocol: TCP
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - mountPath: "/data"
          name: data
      - name: metrics
        image: alpine:3.8
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - mountPath: "/metrics"
          name: data
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data