apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
  labels:
    app: minecraft
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
        version: "1.0"
    spec:
      containers:
      - name: minecraft
        image: openhack/minecraft-server:1.0
        ports:
        - containerPort: 25565
          protocol: TCP
        - containerPort: 25575
          protocol: TCP
        env:
        - name: EULA
          value: "TRUE"
