kind: Service
apiVersion: v1
metadata:
  name: "metrics-service-{{ .Release.Name }}"
  labels: {
    app: "minecraft-exporter"
  }
  # annotations:
  #   prometheus.io/scrape: 'true'
spec:
  selector:
    app: metrics
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP