kind: Service
apiVersion: v1
metadata:
  name: "minecraft-service-{{ .Release.Name }}"
  labels: {
   "type": "minecraft" 
  }
spec:
  selector:
    app: "minecraft"
  ports:
  - name: minecraft
    protocol: TCP
    port: {{ int .Values.minecraft.minecraftPort }}
    targetPort: {{ int .Values.minecraft.minecraftPort }}
  - name: rcon
    protocol: TCP
    port: {{ int .Values.minecraft.rconPort }}
    targetPort: {{ int .Values.minecraft.rconPort }}
  type: LoadBalancer