apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "minecraft-data-pvc-{{ .Release.Name }}"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi